base_url = "https://okay.fail"

title = "okay.fail"
description = "A simple website about things."

default_language = "en"

generate_feeds = true

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"
external_links_target_blank = true
external_links_no_follow = true
lazy_async_image = true
bottom_footnotes = true

[extra]
